version: "3"

networks:
  loki:

services:
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail/config/:/etc/promtail/
      - /var/log/:/var/log/
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9080:9080" 
      - "9090:9090" 
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki/config/:/etc/loki/
      - ./loki-data/:/loki/
    ports:
      - "3100:3100"
      - "9096:9096"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    networks:
      - loki
