networks:
  grafana:

volumes:
  grafana_storage:

services:
  promtail:
    image: grafana/promtail:3.4
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./promtail/config/:/etc/promtail/
      - /var/log/:/var/log/
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9080:9080" 
      - "9090:9090" 
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    networks:
      - grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:3.4.3
    volumes:
      - ./loki/config/:/etc/loki/
      - grafana_storage:/var/lib/loki
    ports:
      - "3100:3100"
      - "9096:9096"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - grafana
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.6.0
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - grafana
    restart: unless-stopped
