devices:
  - device: /dev/ttyACM0
    baudrate: 9600
    logfile: ttyACM0_capture.log
  # - device: /dev/ttyACM1
  #   baudrate: 115200
  #   logfile: ttyACM0_capture.log

  # - device: COM3
  #   baudrate: 115200
  #   logfile: ttyACM0_capture.log
  # - device: COM8
  #   baudrate: 115200
  #   logfile: ttyACM0_capture.log