services:
  wetty:
    image: wettyoss/wetty
    environment:
      - PUID=1000
      - PGID=1000
    user: 1000:1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: --allow-iframe --port=3020 --base=/
    restart: unless-stopped
    privileged: true
    tty: true
    network_mode: host